---
- name: Create Samba configuration directory
  file:
    path: /etc/samba
    state: directory
    mode: 0755

- name: Configure smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart samba

- name: Configure Kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure Samba and Winbind services are enabled
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - samba
    - winbind
