---
- name: Install required packages
  dnf:
    name:
      - samba*
      - krb5*
      - bind
    state: present
    update_cache: yes

- name: Ensure firewalld is stopped and disabled
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Ensure SELinux is in permissive mode
  selinux:
    policy: targeted
    state: permissive
