---
- name: Install Grafana
  dnf:
    name: grafana
    state: present

- name: Deploy Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: 0644
  notify: restart grafana

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
