---
- name: Install Prometheus
  dnf:
    name: golang-github-prometheus
    state: present

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    mode: 0755

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: 0644
  notify: restart prometheus

- name: Enable and start Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started

